Add `encodeEntityId/decodeEntityId` helpers
thefrontside/playhouse pull request #364
Opened 2023-11-06 15:59 UTC by wKich

## Motivation

Sometimes users might write custom resolvers for graphql-plugin, for example they want to query backstage catalog first and then pass received entities further in a graphql query, so entities must be transformed to graphql NodeIds. It's possible to use `encodeId` from `hydraphql` for that, but it's a little overwhelming and not intuitive, because it requires some internal context of `NodeId` type structure.   

## Approach

Simplify encoding NodeIds and provide function that took `Entity` or `EntityRef` as an input and return encoded NodeId string back.

2023-11-06 16:02 UTC, frontsidejack commented
📣 NOTIFICATION
You are receiving this message because we did not publish any packages.
<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions <img alt='Frontside' height='16' src='https://frontside.com/favicon-32x32.png?v=de93ee3512df754fd0cc381d84527025'/></a><em></p><!-- Published Preview Action by Frontside -->

2023-11-07 15:02 UTC, taras requested changes
It's difficult for me to review, because I don't understand how it's supposed to be used. Would you be able to update documentation to explain how to use it?

2023-11-08 14:23 UTC, wKich commented
@taras Added

2023-11-08 15:07 UTC, taras approved these changes
👍

2023-11-08 15:32 UTC, merged