Add batch-loade plugin
thefrontside/playhouse pull request #70
Opened 2022-08-10 11:07 UTC by wKich

## Motivation

Backstage catalog client has `getEntityByRef` and `getEntities` method. The 1st allows to get a specific entity by its reference, the 2nd method allows to get multiple entities which are matched by passed filter. Currently there is no way how to get multiple entities by an array of refs in one request/call

## Approach

Add separate plugin `@frontside/backstage-plugin-batch-loader` that expose `getEntitiesByRefs` with missing functionality. That method allows to retrieve multiple entities by their refs in one call. Which is much efficient than making a lot multiple calls of `getEntityByRef`

2022-08-10 11:11 UTC, frontsidejack commented
The following preview packages were published:
|                                 Name                                 |                       Version                       | Install Command                                                                               |
| :------------------------------------------------------------------: | :-------------------------------------------------: | --------------------------------------------------------------------------------------------- |
| <br><pre><code>@frontside/backstage-plugin-batch-loader</code></pre> | <br><pre><code>0.1.1-dl-batch-loader.0</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-batch-loader@dl-batch-loader</code></pre> |
<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions <img alt='Frontside' height='16' src='https://frontside.com/favicon-32x32.png?v=de93ee3512df754fd0cc381d84527025'/></a><em></p><!-- Published Preview Action by Frontside -->

2022-08-10 15:44 UTC, cowboyd requested changes
Bang up job! Will be so nice to have a fast batch interface. I'm thinking eventually we can get this merged into the core, and it should be doable... all that needs to happen is to add a `entity_ref` field to the `final_entities` table.

We can also add the endpoint at a later date because there are lots of valid concerns about what shape that will take: GET vs POST.... what is the absolute page size, etc... 

Just have a single suggestion to convert the test setup to a resource.

2022-08-10 15:44 UTC, cowboyd commented on plugins/batch-loader/src/tests/loader.test.ts
> +  })
Let's implement `createCatalogPlugin` as an [resource](https://frontside.com/effection/docs/guides/resources). That way, its teardown is implicit, it can be composed freely, and there is no need for an `afterAll()` hook.

```ts
function useCatalogPlugin(env: CatalogEnvironment): Operation<void>  {
   return {
     name: "CatalogPlugin",
     *init() {
        let builder = yield CatalogBuilder.create(env);
        let { processingEngine } = yield builder.build();

        yield processingEngine.start();
        yield ensure(() => processingEngine.stop());
      }
   }
 }
```

2022-08-12 11:48 UTC, wKich commented on plugins/batch-loader/src/tests/loader.test.ts
> +  })
Done

2022-08-12 12:44 UTC, taras approved these changes
👍

2022-08-12 12:44 UTC, taras commented on plugins/batch-loader/package.json
> +  "files": [
Since migrations will execute inside of the container, we need to include the migration files so they can be resolved at runtime.

2022-08-12 12:44 UTC, taras approved these changes
👍

2022-08-12 12:46 UTC, merged

2022-08-12 14:00 UTC, wKich commented on plugins/batch-loader/package.json
> +  "files": [
We have it