Introducing incremental GitHubRepository Entity Provider
thefrontside/playhouse pull request #85
Opened 2022-08-25 14:04 UTC by taras

## Motivation

By providing documentation, we want to make it easier for people to write Incremental Entity Providers. 

## Approach

Did a lot of polishing to do writing, using, and installing Incremental Entity Providers easy.

![giphy-12](https://user-images.githubusercontent.com/74687/186787222-b6b0f788-49d1-4a3e-81e0-a3d584464e67.gif)

2022-08-25 14:08 UTC, frontsidejack commented
The following preview packages were published:
|                                         Name                                         |                                        Version                                       | Install Command                                                                                                                                |
| :----------------------------------------------------------------------------------: | :----------------------------------------------------------------------------------: | ---------------------------------------------------------------------------------------------------------------------------------------------- |
| <br><pre><code>@frontside/backstage-plugin-incremental-ingestion-github</code></pre> | <br><pre><code>0.1.1-tm-incremental-github-repository-entity-provider.0</code></pre> | <br><pre><code>yarn add @frontside/backstage-plugin-incremental-ingestion-github@tm-incremental-github-repository-entity-provider</code></pre> |
<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions <img alt='Frontside' height='16' src='https://frontside.com/favicon-32x32.png?v=de93ee3512df754fd0cc381d84527025'/></a><em></p><!-- Published Preview Action by Frontside -->

2022-08-26 15:59 UTC, cowboyd requested changes
Looks amazing! Have a few fixes to the docs

2022-08-26 15:59 UTC, cowboyd commented on plugins/incremental-ingestion-backend/README.md
> +    await around({ apiClient });
```suggestion
    await burst({ apiClient });
```

2022-08-26 15:59 UTC, cowboyd commented on plugins/incremental-ingestion-backend/README.md
> +    await around({ apiClient })
```suggestion
    await burst({ apiClient })
```

2022-08-26 15:59 UTC, cowboyd commented on plugins/incremental-ingestion-backend/README.md
> +    await around({ apiClient })
```suggestion
    await burst({ apiClient })
```

2022-08-26 16:57 UTC, cowboyd approved these changes
Absolutely bang-up work..

2022-08-26 16:58 UTC, merged