Fix deletion query for incremental ingestion backend
thefrontside/playhouse pull request #95
Opened 2022-09-15 10:43 UTC by wKich

## Motivation

Incremental ingestion backend package has a few issues which were fixed in closed source version.
Fixes #92, #93, #94

## Approach

Sync fixes from closed source version

2022-09-15 11:40 UTC, taras commented on plugins/incremental-ingestion-backend/src/iteration-db.ts
> +        await mark(tx, id, sequence, next.entities, next.done, JSON.stringify(next.cursor));
Can you tell me more about this change?

2022-09-15 12:31 UTC, taras approved these changes
👍

2022-09-15 13:42 UTC, cowboyd requested changes
This looks good. 

It's more apparent with every change that we need to settle on a testing strategy for this deletion logic. Not now, but every time we change it, it's a risk. According to our conversation yesterday, it sounds like we'll need to add deletion to graphgen.

2022-09-15 13:42 UTC, cowboyd commented on plugins/incremental-ingestion-backend/src/iteration-db.ts
> +        removed = (
Let's pull this into a function. This is a big enough blog, that it makes tracking the mutability non-trivial.

2022-09-16 06:48 UTC, frontsidejack commented
📣 NOTIFICATION
You are receiving this message because we did not publish any packages.
<p align='right'><em>Generated by <a href='https://github.com/thefrontside/actions/tree/main/publish-pr-preview'>@thefrontside/actions <img alt='Frontside' height='16' src='https://frontside.com/favicon-32x32.png?v=de93ee3512df754fd0cc381d84527025'/></a><em></p><!-- Published Preview Action by Frontside -->

2022-09-16 06:48 UTC, merged

2022-09-16 06:50 UTC, wKich commented
@cowboyd Oh, I'm sorry, I've merged branch without your approval

2022-09-16 13:04 UTC, cowboyd commented
It looks like we didn't have branch protection enabled.